### ISSUE TITLE
Help bring Artonomous to life!

### ISSUE THREAD

**Issue by tarrencev** [ethberlin-hackathon/ETHBerlin-Teambuilding#19]
## Pitch

In the words of @simondlr, [Artonomous](https://github.com/artonomous/artonomous-mvp) is a self-sustaining, self-improving, autonomous artist.

The premise is that it sells generative art as an ERC721 NFT at a regular interval. The ETH it makes from selling the art gets deposited into a curved bond (SOUL tokens).

Utilizing digital art generators created by humans, it seeds art into them, sells it daily and incentivizes humans to create more generators to sell more art. Owners of the art pieces it sells are owned by them without relying on any other third parties or intermediaries. It is scarce, digital, collectible art.

As part of ETHBerlin, I think it'd be cool to bring one of the variations to life!

## Team

I posted previously to the Artonomous gh and received responses from @sethfork, @EdsonAlcala, and @BenCmjn. I have an engineering/design background and can contribute to smart contract and  front-end development.

## Skills wanted

Based on the github profiles of others who have signaled interest, I think we are a primarily technical group right now. I think someone with a UI/UX background would be awesome! Anyone with experience creating generative art, i.e. training GAN's and VAE's would be super cool too.

## Communication

Join us on Status @ #artonomous!

**Comment by katotopark** [comment]
hiya!
are you peeps still looking? i'd love to get in on this :]

**Comment by tarrencev** [comment]
Hi @katotopark, you're welcome to join! Lets plan on meeting during the team formation on Friday.

**Comment by katotopark** [comment]
looking forward :]

**Comment by maxarca** [comment]
Awesome, I'm very interested. Let's talk on your Status.

**Comment by iainnash** [comment]
@tarrencev Hey! I'm interested in working on this project. will follow-up on Status.

**Comment by tarrencev** [comment]
@iainnash @katotopark @ffakk hey guys, I'm not sure if status chat is working right now. I don't see any messages coming through on my end. I think maybe the easiest way to coordinate is to meet at the team formation this evening? If you guys have any other ideas let me know!

**Comment by BenCmjn** [comment]
Yeah, Status is capricious with me too @tarrencev .. I suggest to meet at the team formation to (specify a spot where to meet maybe) and keep checking this thread. ;)
Today I got a yellow (mentor's) Tee, over a purple shirt, and grey trousers. ^^

See ya!

**Comment by BettinaBF** [comment]
Hey guys, 

I'm super interested, and late, would you still be interested in an extra person?

**Comment by katotopark** [comment]
@tarrencev yea status is a bit deserted :/
i'm around anyways. see you at the team formation ✌️

**Comment by iainnash** [comment]
Hey if people are around before can we meet?

**Comment by tarrencev** [comment]
Hey all, I'm heading over now. I'm wearing a striped black shirt and black
pants. Looking forward to meeting!

**Comment by katotopark** [comment]
i'm in the large ws/talk room sitting on the window sill with headphones.

**Comment by iainnash** [comment]
There are three of us now, have space for two more. on the right windowsill
by the stage.
