### ISSUE TITLE
Hacker looking for team =) 

### ISSUE THREAD

**Issue by jasperdg** [ethberlin-hackathon/ETHBerlin-Teambuilding#2]
#Hacker looking for team

Hi guys my name is Jasper de Gooijer, Ive been a web dev (javascript mostly) dev for a couple of years now for the past 3 months I've been fulltime working on my ethereum stack. I'm from Amsterdam and am 22 years old. 

Skills
- Javascript 
- React
- Web3.js
- Solidity (about 6 months experience) 

Communication

**Comment by Kyrrui** [comment]
I'd be interested in forming a team! I'll shoot you an email tomorrow

**Comment by pascalvanhecke** [comment]
[ a hackathon is meant to be able to connect with people you don't meet otherwise, but still... did you know about http://ethereum.nl?  I am pretty sure some people from NL might be going too, you could repeat your call in the discussions at the bottom of that meetup page ]

**Comment by ghost** [comment]
check this out: https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/58
