### ISSUE TITLE
Decentralized microblogging seeks hacker

### ISSUE THREAD

**Issue by mi-kas** [ethberlin-hackathon/ETHBerlin-Teambuilding#20]
## Pitch 🚀

We at InkDrop want to develop a fully decentralized microblogging platform on eth with no single centralized (or at as little as possible centralized entities) involved. Our goal is to give the users new means of content monetization and at the same time incentivize them for governing the platform (i.e. marking spam, banning trolls etc.). We have a [first boilerplate](https://app.inkdrop.tech/) using the technologies listed below in place and want to add some new cool user incentivation functions to the dApp.

Our idea for the hackathon is to build a „proof of care“ framework/protocol: users can mark spam or trolls etc. and the community itself decides then if it is the case or not. User would get then rewards for governing the platform. This could be extended further by adding expert levels for the users, so that experts in a certain area would have a higher rated vote than others (just as an idea). 

## Team 👯‍♀️👯‍♂️

@jasperdg (22yo dev from Amsterdam) and I (27yo dev from Berlin) are super excited to participate in the hackathon and are looking forward for other hackers to join our idea. 

## Skills wanted  👀

All devs are welcome:
- Solidity
- truffle
- zeppelinOS
- React + Redux + redux-sagas
- Node.js
- drizzle
- IPFS

All designers are welcome:
- UI
- UX
- Wireframes

## Communication 💬

Email: mi.kaserer@gmail.com

✌️

**Comment by jasperdg** [comment]
💪💪

**Comment by ligi** [comment]
Perhaps we should join forces or at least talk/collaborate while the hackathon. I just think it would make a bit more sense to build on something existing (also a power of blockchain technology) instead of rolling something new: https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/32
What do you think?

**Comment by jasperdg** [comment]
We should definitely meet up and discus this @ligi feel free to contact us if you'd like to schedule a call before the hackaton to explore our options.

**Comment by ligi** [comment]
won't really have time before next Friday - let's just talk there.
