### ISSUE TITLE
Hyperglobal Journalism

### ISSUE THREAD

**Issue by sebastiandigi** [ethberlin-hackathon/ETHBerlin-Teambuilding#21]
name: "Hyperglobal" wants hacker
about: a new journalistic format to get closer to the facts**
 ---
 ## Pitch

 "Hyperglobal" is a new ad-free journalistic format built on the blockchain. Curated articles from global quality sources are sourced, translated via AI (hack: deepL) and finetuned by editors to your language. We provide access to local perspectives closer to source. Readers pay per smart micropayments and can stake coins to challenge journalistic dilligence of articles to prevent fake news. 

Target group will be both readers and also other publications. 

 ## Team

 I am an entrepreneur & journalist who has successfully lead a social business and recently built up Gapless (investor was Porsche) as a venture architect, an ethereum-based platform for classic cars (use case: vehicle ID). For Hyperglobal I am in concept phase, currently only working with one designer on it and sounding it with coders and entrepreneurs.  

 ## Skills wanted
**Anybody who is hyped by working on ad-free impact journalism - please join us!**

For this hackathon, we should prioritize micropayments and challenging the journalistic dilligence. For this we need 

- solidity coders with basic infastructure/ geth skills (those skills can be of course divided across several people)
- node.js devs
- full stack devs

We can build on code that CIVIL has developed. (This project is planned to run on CIVIL at some point, too).

Second priority would be the flows and frontend, for which we would highly appreciate

- UX/UI designers 
- react devs

The application will be mobile first at launch - for this very first hackathon where we start from zero, it depends on design ressources if we already start with that.

There are many ends to work on - I feel flexible about working on what suits our skill set most. 

 ## Communication

 Write me on status!
0x04fd579abda53d636fb6be22b5dc88488ef07a3bc73be383cd27ce6b241361f87fd40edcaf446dea6db57c3d62823a6b4fd432176a7ff4150610f59474cd309863

or at sebastian et kancha dot de

**Comment by cesalazar** [comment]
Epa @sebastiandigi, thanks for the invite! This project looks quite interesting to me, and I can definitely lend up to two hands. I'll (try to) reach you in Status.

**Comment by SamTS** [comment]
Project looks very neat, reaching out to you on Status as well (I hope!)

**Comment by BettinaBF** [comment]
Hi, I really like the project, i'll try to reach out to you on status!
