### ISSUE TITLE
Hacker looking for a team

### ISSUE THREAD

**Issue by avichalp** [ethberlin-hackathon/ETHBerlin-Teambuilding#27]
## Background

Hello,
I am Avichal. I am a full stack developer and a beginner in the Dapp ecosystem. This is my first Ethereum hackathon. I am here to learn.

## Skills
Skills relevant to this hackathon:
- JS (React/Angular/node/vanilla/Web3)
- Solidity & truffle (beginner)

## Communication
- [DM](https://twitter.com/_avichalp) 
- Email: *pandeyavichal7@gmail.com*
- Status: `0x041f1f581ac7c87ecb4d5c2d57449a35ffeb27be62a9fe67df3809e78c399f2f8dc6cc7fe30bcbcb9b75b9a1a2d88a19deaf8228221ea0eea298c44a058ce15f5d`

**Comment by jackjdleslie** [comment]
If you're interested have a look at #41, i'm looking to work with and learn from React folk 😄

**Comment by avichalp** [comment]
Hey @cipherpeon Thanks for reaching out. 
I am working with this team for the Hackathon https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/33
Excited to meet you there. All the best :)
