### ISSUE TITLE
Stray full-stack dev looks for team

### ISSUE THREAD

**Issue by cesalazar** [ethberlin-hackathon/ETHBerlin-Teambuilding#28]
## Team wanted!

Terminal lover, willing to get his hands dirty with (almost) anything, looks for lovely (or not) team to help them to interface any ETH related project with the browser.

Comes from Venezuela, does mostly front-end at the moment, and plays on rinkeby from time to time. Has all the vaccines and doesn't bite (most of the time). Curiosity and thirst for knowledge landed him on ETHBerlin, as hanging with the 1337 may transmit him their disease.

## Skillz

Experience with back-end, front-end, and some devops: PHP/HTML/CSS(sass, stylus)/JS(vuejs, preact)/Webpack/Travis-CI. Good understanding of geth, and interacting with it using Truffle framework. Poked around solidity but not enough to produce something useful.

## Communication

Status:
![Imgur](https://i.imgur.com/9X4jdElt.jpg)
0x04437a37bee05e554e735793e0975ea6d6e51b5afa1ab564aaf4fed0fc933cce3c6d9f54cce74cce7f8868a0b8e6bdd635eb703a401e6623f9c9706e82cc67c971

Too _shy_ to leave his phone/email on a public post, ~and no Riot/Status at the moment~ but, please, leave a comment on this issue with a preferred method and details, and he'll join wherever the communications of the team happen. IRC works pretty well too.

**Comment by sebastiandigi** [comment]
hola compadre,
i am looking for full stack devs to join me on the mission to bring international quality journalism back, using crypto as payment and as challenger function --> https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/21

**Comment by svechinsky** [comment]
Hello friend,
We are trying to correct some of the wrong doings of traditional finance, like the way direct debit works.
You can read more about it here https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/33
or message me at yoni@kreator.im

**Comment by ghost** [comment]
if you are interested in curation and the attention economy, check out my project: https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/58
