### ISSUE TITLE
Decentralized marketplace for AI (artificial intelligence) and IA (intelligent assistants) - superpowering human abilities 🔥🔥🔥

### ISSUE THREAD

**Issue by stefek99** [ethberlin-hackathon/ETHBerlin-Teambuilding#29]
# Idea needs team 😎

![](https://media.giphy.com/media/26n78QtJt4LHeNXi0/giphy-downsized.gif)

### Goal

Make better decisions, when the timing is critical and I do not have access to full information.

I want to enhance (superpower) my human abilities.

Just like Siri, Alexa, Cortana but combined with real human intelligence.

There could be a human operator - concierge - responding to my queries. A pool of 10 operators could handle 100+ customers, with similar to Uber “surge pricing” in the periods of high demand.

### Prototype

Cheap Android device streaming all the time,

* Data transmission - cost going to zero
* Storage - cost going to zero
* Battery - getting better and better

Feed can be public or private.

More advanced version would involve 360 camera.

More discrete option would involve camera in the glasses, not to freak out other people.

Think https://en.wikipedia.org/wiki/Justin.tv but 10 years later (technology exponentionally better) with blockchain marketplace incentives and people already becoming cyborgs, streaming live all the time and consuming mucho mucho media.

### Use case

Sometimes I am presented with a decision - when the priorities are set straight, it’s easy to make the right choice. But sometimes I’m missing full information, there are other parties involved, there are conflicting priorities, each option is equally good or equally bad - I want to access my support network.

“Normal” people would call a friend or a family member, I’m a little bit autistic and I struggle to maintain healthy relationships with other humans. Meeting new people OK, social situations OK, just constant travel (decentralization) and bumping into same guys at conferences hardly count as meaningful relationship.

> DISCLAIMER: I’ve identified the pattern, I’ve been actively working on it, I have a few buddies I can call at any time and ask for advice

### Privacy concerns

Some people are concerned about privacy, surveillance.

Some people are outraged by Snowden “revelations” and Cambridge Analytica using FB data to efficiently target US and BREXIT voters.

There is nothing surprising in the fact that government wants to govern, it is nothing surprising that campaign teams want to spend their marketing budged efficiently.

10 years ago [Obama was praised was use of social media](https://en.wikipedia.org/wiki/Barack_Obama_presidential_campaign,_2008#Social_Media) and appealing to younger generation. Now it appears to be a surprise that other guy is using modern technology to target voters.

**I always assumed that I’m already hacked.**

*(hanging out at CCC, SHA, EMFCAMP)* 

I have no way of recourse against state actor and / or sufficiently motivated attacker.

[![XKCD](https://user-images.githubusercontent.com/249703/44802553-f30cd400-abb3-11e8-93f2-9ba0344616d6.png)](https://xkcd.com/538/)

I don’t trust my hardware ([intel management system](https://en.wikipedia.org/wiki/Intel_Management_Engine)), software, operating system, ISP, DNS, browser.

Even if I use completely open-source laptop just like Richard Stallman, Free Software Foundation, I do not have enough expertise to verify authenticity of all the drivers.

I just assume I’m a small fish and there no game theory incentives to hack me. If someone wants to hack me, there is always a way, regardless how much energy I’ve spent on protecting myself… Rather than playing of who has better encryption, who has deeper underground bunker, whose tin foil hat is more radiation resistant.

* On my personal wiki I call it “Everything in Public”: https://genesis.re/wiki/#Everything_In_Public
* Bob Summerville calls it “Open by Default” https://bobsummerwill.com/conflict-of-interests-statement/
* Some Burning Man folks would call it “Radical Transparency”

### Social concerns:

https://en.wikipedia.org/wiki/Neil_Harbisson

https://en.wikipedia.org/wiki/Cyborg_Foundation

Some people still may feel weird.

We still have a long way to go.

### Ethical concerns 

“Survival of the Richest” - https://medium.com/s/futurehuman/survival-of-the-richest-9ef6cddd0cc1

$200k on biohacking: https://hackernoon.com/im-32-and-spent-200k-on-biohacking-became-calmer-thinner-extroverted-healthier-happier-2a2e846ae113

Those with the access to such tools will have massive competitive advantage against regulars. 

The gap is already happening - having personal chef, personal trainer, all the supplements and vitamins surely help maintain the edge.

### Economy

As a student in Krakow, Poland I was working on a click farm, sending invites on MySpace to a dating site. $2 per hour, that was 2 beers in a pub.

_(don’t put me into jail for breaking Terms & Conditions of a website that is long gone)_

2 beers in a pub in London is roughly £10, London living wage: https://www.livingwage.org.uk/calculation

[![image](https://user-images.githubusercontent.com/249703/44802785-86460980-abb4-11e8-91b4-29a841d24870.png)](https://www.bbc.co.uk/news/world-latin-america-45246409)

I’m morally OK to pay $1 per hour, one operator can monitor many feeds. We can agree on some minimal statutory **satoshis per second**, but I'd rather allow free market to work.

At some point my data can become a commodity and DAI (decentralised autonomous intelligence) will bid to have priority to access or exclusivity.

---

# Do you know existing projects of this type?

We Live in Public: https://www.imdb.com/title/tt0498329/

> Among Harris' experiments touched on in the film is the art project "Quiet: We Live in Public," an Orwellian, Big Brother concept developed in the late '90s which placed more than 100 artists in a human terrarium under New York City, with myriad webcams following and capturing every move the artists made.

**Comment by stefek99** [comment]
About ethical and privacy concerns...

https://www.linkedin.com/pulse/adi-shamir-makes-15-predictions-next-years-andreas-sfakianakis/

> 11. Most people will not demand or expect real privacy; that war is already lost.

https://en.wikiquote.org/wiki/Edward_Snowden

> Arguing that you don't care about the right to privacy because you have nothing to hide is no different than saying you don't care about free speech because you have nothing to say.

https://en.wikipedia.org/wiki/Nothing_to_hide_argument

---

I see things differently.

https://github.com/alex/what-happens-when

As explained initially - I don’t trust my hardware, software, operating system, ISP, DNS, browser. Not playing game who has better encryption, who has deeper underground bunker, whose tin foil hat is more radiation resistant. **I always assumed that I’m already hacked.**

I want to use extra intelligence, I actually think it is already happening - people posting statuses on Facebook / Twitter / Instagram - who can borrow a bike, who know this and that, where do I find... Now adding incentives, and now as I think about it - blockchain not required - a lot of things can work perfectly without a blockchain.

Example: Open Bazaar. Using Bitcoin and other crypto as payment, did not need Open Bazaar Coin to function.

**Comment by stefek99** [comment]
Update: https://twitter.com/MichalStefanow/status/1035843631448502272

_(cannot make it)_

**Comment by marsrobertson** [comment]
This one: https://soranews24.com/2018/11/29/cafe-opens-in-tokyo-staffed-by-robots-controlled-by-paralyzed-people/

![image](https://user-images.githubusercontent.com/44369284/50632838-7450ea80-0f49-11e9-96c7-afbdf6a3ca86.png)
