### ISSUE TITLE
Anton from Thetta.io

### ISSUE THREAD

**Issue by AnthonyAkentiev** [ethberlin-hackathon/ETHBerlin-Teambuilding#3]
## Background

Founder of Thetta DAO Framework. Please check https://web.thetta.io
We are open source + task tracker is open too.

## Skills

Ready to write smart contracts.
solidity, web3.js, truffle

## Communication

t_on_y@thetta.io (please remove underscores)

But better write me directly here)

p.s. Somehow can't add a label to the current issue. Please set the "Hacker wants team" label )

**Comment by s1na** [comment]
Hey @AnthonyAkentiev, great to have you here :) I was wondering what happens when you try to set the label? so that we can fix it

**Comment by AnthonyAkentiev** [comment]
@s1na I just have no permissions to set the label i think(
I can't set the milestone (etc) too. Thx for help!

**Comment by sebastiandigi** [comment]
Hey Anton, interesting thing you have with Thetta! Might be applicable to my journalism concept too, https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/21 - looking for solidity dev still!

**Comment by yasinskyy** [comment]
Hi @AnthonyAkentiev 

I am a member of team that consists from 3 enthusiastic developers that are going to visit ETHBerlin and take part in the hackathon. We are working on a project that will allow to combine the power of blockchain and smart contracts with ease of use and beautiful design for end users. If you are still interested in finding a team, please let me know. Would be great to work with somebody like you. Thanks!

All the best,
Yuriy

**Comment by AnthonyAkentiev** [comment]
@YuraYasinskyy Hi! 
Yes, selecting the team right now. 

Could you please describe:
1) Project idea
2) Team

Please write me to:
t_o_ny@thett+a.io (remove symbols)
