### ISSUE TITLE
libre Android Peepeth client

### ISSUE THREAD

**Issue by ligi** [ethberlin-hackathon/ETHBerlin-Teambuilding#32]
## Pitch

I think it would be great to have one libre Android [Peepeth](http://peepeth.com) client with nice mobile UX. There was one hackathon recently spitting out a iOS client: https://github.com/matterinc/PeepethClient - and IMHO there really should be one Android client. Perhaps leveraging [WalletConnect](https://walletconnect.org) + [WallETH](https://walleth.org)

## Team

currently it is [just me](https://ligi.de) - but the idea is also very fresh ;-)

## Skills wanted

* Graphics / UI / UX
* Kotlin
* Reverse Engineers
* Tester
* JavaScript
* Solidity ( can also do without as we can interface with the existing contract - but could also be nice as the existing contract does not live on a test-net and I would love to test things on a testnet. So could also be nice to code a contract fulfilling the current peepeth API and deploy it on the tesnets)

## Communication

I would prefer riot/email/face2face - and for sure peepeth(dogfooding FTW - I am https://peepeth.com/ligi there) - but I am open to suggestions.

**Comment by ligi** [comment]
For people that want to join - would be great if you could [get an account first](https://peepeth.com/?PeepethLoves=ligi) as it might take a bit to get it (is currently in "invite only mode" - which basically just means you cannot get an account instantly - takes usually one day or so)

**Comment by ihlec** [comment]
https://peepeth.com/crnls - feel free to follow or peep

**Comment by skywinder** [comment]
hi, @ligi ! My team made PeepEth iOS client. the idea is very cool and I would like to talk with you about our idea for this hackathon on ETHBerlin. How Can i reach you? my telegram and twitter @skywinder btw :)

**Comment by skywinder** [comment]
hi, @ligi ! My team made PeepEth iOS client. the idea is very cool and I would like to talk with you about our idea for this hackathon on ETHBerlin. How Can i reach you? my telegram peep and twitter @skywinder btw :)

**Comment by jeluard** [comment]
@ligi Is the code for this available?

**Comment by ligi** [comment]
@skywinder nice meeting you at the event!
@jeluard sure thing here the code: https://github.com/ligi/PeepDroid | here some more information: https://devpost.com/software/peepdroid - will also release to play and f-droid soon - just have to smoothen some rough edges

**Comment by jeluard** [comment]
@ligi Awesome thanks!
