### ISSUE TITLE
hermes.network - distributed executors earning gas by relaying transactions

### ISSUE THREAD

**Issue by hellwolf** [ethberlin-hackathon/ETHBerlin-Teambuilding#35]
## Pitch

In many DApps or DAOs that have its native token system, it would be convenient for the participants only with the native tokens and not with Ether at all. This way, participants would only need to purchase one single type of token.

The *gas sponsors network* is here to solve the problem. It is a p2p messaging network with pubsub semantics (very likely we would just use the eth whisper protocol), where the participant sign a signature of delegated actions and associated rewards, then broadcasts the signature to the network. The first sponsor that takes the signature and fund the Ethereum transaction would claim the reward.

By standardizing the format of the delegated actions and associated rewards, anyone can then use this network to achieve a "Ether-less" DApp or DAO.

### Technical Details

With the help of `ecrecover` function in solidity, it is possible to allow third-parties to "sponsor" gas to fund the on-chain transactions on behalf of the participants. To do so, the participant needs to sign the approved actions (understood by the smart contracts) with their private key, and communicate the signature to the "sponsor" off-chain. The smart contracts needs to understand the actions and prevent signature "replay attacks", with the help of nonce for example.

There are several implementations using this technique for specific use cases, for examples:

- https://github.com/ethereum/EIPs/issues/965 - Send by Signature (ERC777 extension) - transfer without paying for gas
- https://github.com/noia-network/noia-governance/blob/master/contracts/noia/v1/NoiaWorkOrderV1.sol - Delegated calls pattern

### MVP

- Draft standard for the gas sponsor bounty contract interface
- Minimum Gas sponsor node software
- Examples

## Team

I'm the architect and blockchain developer from noia.network team. We use Ethereum as our platform to implement a bandwidth sharing marketplace. Me and another blockchain developer of noia.network are coming to the event together for this proposed project.

## Skills wanted

* Backend developer, nodejs/type script, etc.
* web3 developer, preferably familiar with whisper protocol

## Communication

- Telegram: https://t.me/miaozc
- Status address: 0x0421b6bcfcfcf4bbc45a03eb703aea3ed6daeeb884e41b6033f8e3391ddbcfed068f03103081fdbc2e2273c822a5751311b93b1b7e71bd85ece2ce0bebe5798544 (still don't know how to use it well...)

**Comment by gluk64** [comment]
Hey @hellwolf, this sounds very interesting!

**Comment by hellwolf** [comment]
Also found https://github.com/ethereum/EIPs/issues/865 today.

**Comment by PhABC** [comment]
You guys should talk with @lsaether from Chronologic about your idea (he will be at EthBerlin). One problem I see with your current design is that it's inefficient, meaning a lot of people will try to execute a transaction but will fail (since only the first succeeds). This risk of failure has a cost and will most likely mean that "executors" will expect higher rewards to cover this risk, increasing the cost for users. 

Anyway, reach out to Logan, he would happy to talk more about your idea.

**Comment by s1na** [comment]
I'm also starting to work on something related, and would love to join the conversation, if you guys were to meet at ethberlin.

**Comment by hellwolf** [comment]
@PhABC thanks for the lead, tried to reach Logan out on linkedin.

@s1na yes, we will be in EthBerlin.

**Comment by lsaether** [comment]
Hey @s1na I've seen your post on ethresear.ch and would love to meet up at EthBerlin. 

@hellwolf I'll respond to you via LinkedIn. Likewise, let's meet up!

**Comment by s1na** [comment]
@lsaether @hellwolf I'm at the Görlitzer park venue, in the yard. Any chance you folks are around for a chat?

**Comment by hellwolf** [comment]
Yes @s1na , my telegram is @miaozc. let's meet somewhere near the entrance

**Comment by mariapaulafn** [comment]
Hey @hellwolf we're doing a UX workshop at 6:45pm today, would be great if you joined and present your project with us <3

**Comment by hellwolf** [comment]
Hi @mariapaulafn certainly, where is the ux workshop happening?

**Comment by gluk64** [comment]
Hey guys, what did you end up building?

**Comment by s1na** [comment]
Hey @gluk64, the team built a prototype of the concept, about which you can read more [here](https://github.com/hermes-network/hackathon).

I've started work on an [implementation](https://github.com/planet-ethereum/relay-network) geared towards modularity in Go, would love to have anyone who's interested onboard.

**Comment by hellwolf** [comment]
@s1na Thank you for taking this to the next stage. I believe the community will benefit from your continued work! I will definitely be interested in testing your network out, let me know if anything I could help any time.
