### ISSUE TITLE
Debtor DAO

### ISSUE THREAD

**Issue by bohendo** [ethberlin-hackathon/ETHBerlin-Teambuilding#38]
Hello I'm Bo! I'll be attending EthBerlin with [Shivani](https://github.com/shivgupt) and we can't wait to join forces with other hackers who are as excited as we are to see Ethereum's open, decentralized financial services eat the closed, permissionful legacy systems.

## Pitch

We're inspired by the idea of a debtor DAO. Traditional corporations have the ability to raise funds via debt as well as equity and we'd like to enable this option in the world of DAOs as well.

We'd like to build a DAO that utilizes the crowd-lending feature that was proposed by a recent Dharma Improvement Proposal ([DIP-4](https://github.com/dharmaprotocol/DIPs/issues/4)). Using this feature, we could tap into a crowd of investors who might give loans to our DAOs. In parallel, we could do equity-style fundraising using the native token built-in to systems like DAO Stack.

Let's consider the example of a DAO tasked with building an apartment complex (or any other project that requires large up-front funding). After construction finishes, the DAO might have a collection of non-fungible tokens to sell, each representing one of the newly built apartments. Two categories of outcomes are possible:
 1. It sells these tokens for as much or more than expected and receives a large payout. This funding goes *first* into repaying the loans with agreed-upon interest and then the rest is used to make the equity holders fabulously wealthy.
 2. In a less desirable situation, maybe we have trouble selling the apartments or something goes wrong during construction. We'd sell what we can & liquidate the rest of the DAO-controlled assets to pay off as much of the debt as possible. The equity holders get what's left, if anything.

In this way, we insulate the creditors from as much of the risk as possible. Those without any domain knowledge (eg pension funds who know nothing about building an apartment complex) can still invest their money with some kind of assurance that they'll get paid unless things go terribly wrong. Meanwhile, those with deep domain knowledge (eg construction companies) can have skin-in-the-game and be incentivized to help the project be as successful as possible.

We're imagining something that looks like [Alchemy](https://alchemy.daostack.io/#/) plus an interface for investors to buy equity and for creditors to loan money. The equity holders would then be able to vote on issues like how the money is spent, what interest rate the DAO would borrow at, etc.

We're still brainstorming the details of this project but this is the direction that inspires us. If it inspires you too, please get in touch. "Personal Stiff Brahmanbull" said on status that teams can be up to 5 people so we'd love to meet 3 other hackers who want to help build an interface for crowd-lending to a DAO.

## Team

I got obsessed with Ethereum a little over a year ago & walked away from a cushy full-time job to hack with Ethereum full-time instead. In the last year, I've had fun working on a [cryptokitties autobirther](https://gitlab.com/bohendo/ck-mill) and a [blackjack tip jar](https://gitlab.com/bohendo/bjtj).

My teammate Shivani worked as a software engineer at Intel but she recently quit her job to hack with Ethereum full-time too. She's was recently working on a [CLI tool for interacting with MakerDAO](https://gitlab.com/shivgupt/makerkeeper).

We both have extensive experience working with EthereumJS, Web3.js, Truffle, and Solidity. Recently, we've been working together to write a smart contract that would extend the Dharma lending protocol  allow creditors to list their intentions to lend money ([DIP-1](https://github.com/dharmaprotocol/DIPs/issues/1)).

We'd like to use this Hackathon as an way to super-charge our knowledge of DAOs. Ideally, we'd build some new skills and merge them with tech that we're already fluent with eg Dharma and MakerDAO.

## Skills wanted

The most important skill is the meta-skill: being able to ramp up with new tech. We'd like to find synergy between multiple projects which means learning how multiple projects work and how they might plug in to each other.

The plan is to do most of our development in Javascript. We may write some solidity but the focus will be on reading & understanding the smart contracts we're working with.

We're both relatively full-stack so if you have a strength/passion, either of us should be able to adapt & fill in your weaknesses (but no, we will not just write tests while you do all the fun stuff 😂).

Neither of us are particularly strong front end developers; we both know how to use React.js but we're not very good at it. If you're a front-end ninja then we'd be extra excited to join forces with you.

## Communication

Leave a comment here or join the discussion on Status in #ethberlin-debtor-dao

You can also get in touch w me directly at:

![status-qr](https://user-images.githubusercontent.com/8527067/44971095-e7cdf580-af71-11e8-98aa-4f4a76ed2f79.jpg)

0x04c3ffa0198ffd26985eb1d25fb900632d27739eb0032a53e83373d3ea34e09bc60b5f4b3acf5c15e64f9e5f699260f95ce0e27289d8f82af12bf676279c501c6f

**Comment by AnthonyAkentiev** [comment]
@bohendo @shivgupt Hi. My name is Tony and i am from Thetta DAO Framework (https://web.thetta.io)
Your idea looks interesting.

Looking forward to building the app with you. We can use our library to set the permissions, etc.
We can also build the app without the lib. 
The only "problem" is that my specialization is Solidity and we will need a good frontend guy)

Could you please write me? t+o+n+y@thett+a.io (remove plus symbols please)

**Comment by bohendo** [comment]
Hey Tony! I see you've published some interesting articles on Medium, I enjoyed browsing through those. We're thrilled to have someone with your background interested in working with us, Email incoming!
