### ISSUE TITLE
Hacker Wants Team - Rachel

### ISSUE THREAD

**Issue by RachBLondon** [ethberlin-hackathon/ETHBerlin-Teambuilding#4]
## Hacker wants team

My name is Rachel, and I am currently working at Lisk as a Tech Evangelist. I have 3 years experience working as a developer with react/node (react is my preference). I have worked with solidity as a hobbyist, but not professionally.

## Skills

* React + Redux
* frontend Javascript
* Node.js
* Presenting / ideation

## Communication
contact me on
[Twitter](https://twitter.com/RachBLondon)
email rachblondon@gmail.com

**Comment by RachBLondon** [comment]
@casparschwa I don't think I have the rights to add a label  😞

**Comment by NoahMarconi** [comment]
Sent an email. Looking forward to chatting more

**Comment by sebastiandigi** [comment]
hey, if you are interested in ideating and conceptualizing on journalism topics, join our team here: https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/21 :)

**Comment by ghost** [comment]
if you are interested in the attention economy and blockchain-powered curation, consider joining me for https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/58
