### ISSUE TITLE
eWASM Tooling

### ISSUE THREAD

**Issue by s1na** [ethberlin-hackathon/ETHBerlin-Teambuilding#40]
### Introduction
EVM is the part of Ethereum's protocol, that performs contract computations, handles state, tracks how much gas was consumed by a transaction, etc.

eWASM projects aims to replace EVM with a restricted subset of [WASM](http://webassembly.org/). Please refer to the eWASM [design spec](https://github.com/ewasm/design), to read more about the why and how.

### Ideas
Due to its nature, working on eWASM will give you a great insight into how the Ethereum machinery works, and can be a rewarding experience. If you're interested, here are a couple of ideas for contributing to the development of eWASM:

- Integrating eWASM into existing clients, by adding support for [evmc](https://github.com/ethereum/evmc), which is a low-level ABI between virtual machines (EVM1 and eWASM) and Ethereum clients.
- Extending the [Rust API](https://github.com/ewasm/ewasm-rust-api) and the AssemblyScript API to make writing contracts in Rust and AssemblyScript respectively easier.
- Facilitating the transition from EVM1 to eWASM by working on the first prototype of [yevm](https://github.com/axic/yevm) or improving [runevm](https://github.com/axic/runevm).

If you're feeling more courageous, consider tackling one of the following:

- A basic prototype of the eWASM VM implementation, similar to [Hera](https://github.com/ewasm/hera).
- Adding eWASM as a compilation target for smart contract languages such as Solidity and Vyper.

However, these are just some of the possible topics. Feel free to come up with your own ideas.

### Mentors
If you're interested in taking up any of the aforementioned ideas, or have ideas of your own, we can arrange for a mentor to help you during the hackathon. If you have questions about eWASM or the ideas, you can join the [gitter](https://gitter.im/ewasm/Lobby).

**Comment by AnthonyAkentiev** [comment]
@s1na Awesome idea!
Have you checked what Parity is doing? https://paritytech.io/wasm-smart-contract-development/
They have WASM support (i think already implemented) in their node software.

**Comment by s1na** [comment]
Hey @AnthonyAkentiev,

I was aware that Parity is developing WASM libraries and plans to use them in Polkadot, but didn't know they already include support for WASM contracts on Kovan! Thanks for pointing that out.

I had a quick look, and it seems to be a parallel effort to some of the pieces of eWASM. It's possible to write contracts in Rust using their [API](https://paritytech.github.io/pwasm-ethereum/pwasm_ethereum/), which is cool. I'm not sure however if they plan to make it compatible with eWASM when it's ready.
