### ISSUE TITLE
[ÐApp] Decentralised meet-up app, create a meet-up group with no subscription fees

### ISSUE THREAD

**Issue by jackjdleslie** [ethberlin-hackathon/ETHBerlin-Teambuilding#41]
> An example use case of a ÐApp is making economically viable other business models that have seen low uptake or aren't economically viable without blockchain tech. So-called sharing economy business models (which are more aptly called tasker or rentier capitalism models) like Airbnb, Uber, AirTasker, Fiverr, Upwork, TaskRabbit, and Menulog are particularly ripe for transformation (the term transformation is preferrable to disruption, since it should be a net positive change, while negative effects are manageable or solvable), since no trusted third party for a transaction is needed, such as banks 🏦, credit card 💳 companies or PayPal, just a smart contract
> 
> Source - [Ethereum Wiki](https://github.com/ethereum/wiki/wiki/Decentralized-apps-(dapps))

## Pitch

A promise of ÐApps and smart contracts has been that you could disrupt traditional business models, decentralising a system and cutting out middle-men. However, why would a consumer _actually_ use a ÐApp over a centralised app? Despite it being really cool, **decentralisation itself is not enough of an incentive**. Users want an app that has a great UX and is cheaper than the alternative, and so far centralised apps have been fine at providing this. So what business model is ripe for disruption, and could a ÐApp provide those benefits (and could it get a good first version built in 36 hours)?

The Meetup.com app (among others) provides a way for users to create a local meet-up group, advertise it, and create events for people to join and discuss. However, to create and host the group you pay the central authority $14.99 a month. _What if there was a way to eliminate this central authority?_ 🤔

I propose a ÐApp that allows users to create a meet-up group which is represented by a smart contract, and assigns the meet-up group contract an appropriate ENS subdomain (think berlinblockchain.meetupdapp.eth). The meet-up group contract has an owner (organiser) that can set the name, description, categories, logo (IPFS?) etc, and create events hosted by the meet-up group. A new user should be able to sign up, say their interests and location, and find a suitable meet-up group they can join.

Pros:
- No subscription costs required, just the one time set up fee for the associated gas cost when interacting with the ÐApp
- Using ENS provides a huge usability boost, having a group sub-domain abstracts over contract addresses.
- Can send donations directly to the contract, which the organiser can withdraw and put towards beer funds
- Users wanting to join a meet-up group have to pay gas (possibly a signing up fee, organiser dependant?) to alter meet-up contract state, so you could argue that ghosts members might be reduced.
- Room for a [BlockParty](http://www.noblockno.party/) integration with events

Cons:
- Using a ÐApp still has a high barrier to entry (needing to use MetaMask or appropriate ÐApp browser), so from our end it's important to make the ÐApp as user friendly as possible (ultra responsive, reduce amount of contract method calls needed, mainly contract state reads)
- Please add some criticisms below

## Team

Just me at the moment, I'm an undergraduate CS student from Scotland. I interned as an Ethereum developer this summer, and took part in the ConsenSys Developer Program. I've been working mainly with Solidity, Truffle and React and looking for further experience in all 3, particularly in React and Redux.

## Proposed Stack

Solidity and React (possibly with Drizzle).

## Skills wanted

This project will need hackers well versed in smart contract development to create a good contract infrastructure, as well as front-end engineers who like working with web3 and want to make a sweet responsive UI.

## Communication

DM me on Twitter at @jackjdleslie, or on Keybase @cipherpeon

## Disclosure

_I built a **very** basic [prototype on Rinkeby](http://societhy.herokuapp.com) for this idea earlier this summer, however if there was interest in this idea I'd like to spend the hackathon building it properly with others from the ground up with **completely new code and infrastructure**_

**Comment by JohannesHa** [comment]
Nice! I sent you a DM on Keybase :)

**Comment by ghost** [comment]
this is needed and its the right time. 

i have an idea myself (https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/58) but your project would be my second preference. so lets chat during team formation!

**Comment by jackjdleslie** [comment]
Code:

https://github.com/JohannesHa/meet-up

Submission:

https://devpost.com/software/meet-up-gdi1xk
