### ISSUE TITLE
Banlist via prediction markets

### ISSUE THREAD

**Issue by s1na** [ethberlin-hackathon/ETHBerlin-Teambuilding#43]
### Introduction
Spams and scams are rampant in the whole crypto-ecosystem. In order to protect users, some teams are maintaining a banlist manually, such as the MetaMask [eth-pishing-detect](https://github.com/MetaMask/eth-phishing-detect) for websites, ENS's [blacklist](https://github.com/ensdomains/blacklist) for ENS domains, etc. But it's costly and requires increasingly more effort to maintain the list.

This proposal outlines one possible solution to maintain a banlist in a scalable and decentralized manner, by employing prediction markets.

### Method outline
The basic idea is that a user would create a small bet to claim a particular item should be on a banlist. If nothing happens, the item is added to the banlist. However, anyone can disagree by putting a bet in the other direction. In the end, the side having the majority vote wins, and receives 75% of the other side's shares, the other 25% could be burned. The other side loses 100% of their share.

Please refer to the "Scaling adjudication with prediction markets" section of Vitalik's [post](https://ethresear.ch/t/list-of-primitives-useful-for-using-cryptoeconomics-driven-internet-social-media-applications/3198) for details on how the mechanism works, and its characteristics.

### Possible Use cases
- A banlist for scam domains (dns & ens)
- A banlist for social media users, or specific messages, that aim to scam users

**Comment by bijanshahrokhi** [comment]
Interesting idea. I am a product manager and interested in contributing. Let me know if you are interested.

**Comment by kolinko** [comment]
Did you look into the concept of Token Curated Registries? You could call it a subset of prediction markets designed to facilitate a creation of lists. Trent McConaghy wrote some medium posts on the subject.

Also, if you want to bounce some ideas about the economic/token design, chat me up.
