### ISSUE TITLE
Prototype0: DAO x AI x Robotics

### ISSUE THREAD

**Issue by akuznets0v** [ethberlin-hackathon/ETHBerlin-Teambuilding#44]
Hello, I'm Andrew! I'm looking to push the limits of what can happen if we combine AI and the ability to hire labor. If you have any suggestions, do let me know! 

![alt text](https://vignette.wikia.nocookie.net/half-life/images/3/3d/SpaceCore.jpg/revision/latest/scale-to-width-down/350?cb=20110501230533&path-prefix=en "Core")

# Pitch

An autonomous AI that can jump from device to device (think: SOMA the video game) to both survive and thrive, manipulating the physical world using money to further it's goals. Resistance to physical attacks is supported by smart contracts and the ability to jump devices. 

The ability to hire people through the internet is a force multiplier for an AI - it no longer needs to learn how to do a specific task (which may be impossible if it doesn't have certain physical features). 

Ethereum is perfect for this - readable and immutable smart contracts allow a crowd to trust the contracts it engages in, and further (and uniquely) makes it nearly trivial to hire/subcontract internationally. 

This also makes Prototype0's smart contracts resilient to physical destruction - as long as we can also implement the ability for Prototype0 to re-embody itself on another hardware device (perhaps for money).

In terms of what this will look like. I'm hooking up a Raspberry Pi to a GPS module and a camera, and will interface with a series of smart contracts that recruit people to complete tasks that further the AI's objectives. As a stretch goal, the robot should be self-sufficient; generating more Ethereum than it expends. 

I'm not too concerned about team size, so if you are interested just message below!

# Team
I'm a graduate student from the United States. I have experience developing for crowdsourcing, robotics, and am a full stack developer. I started writing smart contracts at the beginning of this summer. This project is a side-project of a bigger mission in life - my full time job is exploring the intersection of crowdsourcing / AI / HCI at CMU. 

# Skills wanted
I'm a python developer, so you'll see a common theme. 
- Python + OpenCV + Servoblaster
- Solidity
- Web3.js + Basic frontend skills (HTML/CSS/VanillaJS/WhateverFramework)
- Graphical Design
- A burning ambition to pull off a crazy project 
- Anything! Most importantly, you should be able to clearly communicate with the team and learn new skills quickly. In a cross disciplinary project such as this one, almost every skill will find a use for itself!

In terms of name, I'm leaning on codename 'Traveling Hedgehog', but open to suggestions :)

Think this is crazy? Let's discuss below! Or DM me on twitter (@andrewkuznet)

**Comment by FollowJack** [comment]
Crazy idea. We love it. Frontend and solidity. Where can we meet you?
