### ISSUE TITLE
State Channels for Private Transctions

### ISSUE THREAD

**Issue by NoahMarconi** [ethberlin-hackathon/ETHBerlin-Teambuilding#46]
## Pitch

What happens off chain is not only fast, it's private. For this project I'd like to route asset transfers through a hub node to mask the source and destination addresses.

This layer of privacy is what's missing for use cases like loyalty rewards and points to be able to run on the public network.

## Team

I'm a researchers and developer who jumped into blockchain early 2017. I love on/off chain hybrid solutions and recently placed at the BlockHacks event in Toronto.

I'm comfortable working in Solidity, JS, Scala and Python.

## Skills wanted

Looking for a designer or front end dev to help show things off. The state channel interactions will be backend but it would be amazing to demo direct versus indirect private transactions on the front end to tie it all together.

**Comment by 0xrafi** [comment]
hi there,
Are you still looking for a team? We are two developers with experience in frontend and familiarity with solidity.

**Comment by NoahMarconi** [comment]
hey, I did find a team; we're working on something different now. There's three of us, room for two more if you didn't find one yet.

We're going to work on a nucypher related project based on what we saw them present yesterday. 

Did you find a team?
