### ISSUE TITLE
Fact check bounty

### ISSUE THREAD

**Issue by nolash** [ethberlin-hackathon/ETHBerlin-Teambuilding#47]
## Pitch

Ideally, when consuming news, we should fact check claims. However this is time-consuming. So often, you don't. Either, you assume they did their job, or you let someone else do it.

If you're letting someone else do it, is it possible to attach a bounty for fact checking? To verify the references in the news piece really supports its claims. Verify that the chain of references to the source? Produce other supporting or disputing claims of evidence, maybe even to a primary source?

Imagine a network where the participants are distributed among any bias, and the evaluation of evidence is the job of a randomly selected subset of these participants. Those offering evidence deemed valid, will receive a part of the bounty. The bounty could also be upped by others interested in verifying the same.

Maybe this could be read for inspiration

https://www.theatlantic.com/politics/archive/2016/12/what-journalists-can-learn-from-david-fahrentholds-trump-coverage/511277/

## Team

This is currently just an idea. ETHBerlin could be an appropriate venue to try to make something tangible out of it.

I'm a self-taught binary enthusiast, lately working on development for Ethereum Swarm, specifically authoring the implementations of PSS (messaging layer) and the first iteration of Mutable Resource Updates.

## Skills wanted

* Solidity
* Javascript
* Someone who knows about the economics of such things

## Communication

Since I don't use a smart phone (it's the most evil device in history, didn't you know?) I can be contacted on https://gitter.im/nolash or grab hold of me at the event; I'm either in a digit covered red shirt with white collar or an orange swarm hoodie.

**Comment by kolinko** [comment]
I remember talking to people from Gnosis on EdCon about this - if I'm not mistaken they have a project in the works related to fact checking using prediction markets, and some partnerships ongoing as well.
