### ISSUE TITLE
Token economy for organic waste

### ISSUE THREAD

**Issue by nolash** [ethberlin-hackathon/ETHBerlin-Teambuilding#48]
## Pitch

Recently I've met someone who holds a patent to dramatically increase the efficiency of energy output from mining and processing natural gas emission from landfills.

The idea is to crowd-source investment for these installations, theoretically giving participants of any size access to the returns of medium-scale energy projects. When the ROI is reached, the participants would have free energy from the installation, which could be sold on or for example used for crypto mining. The installations can work on- or off-grid.

The fuel? Organic waste. And in the west, you actually _get paid_ to receive waste. In this scenario, it's like getting paid to fill up your car. In other parts of the world, there is no infrastructure for waste management. Could the spoils of the waste surplus of the west be used to sponsor waste management in the subservient neo-colonial reaches of the world?

And: Can we tokenize all this?

## Team

The energy tech is ready to go already. This is a real-life project that needs a team to build the crypto infrastructure around it.

I'm a self-taught binary enthusiast, lately working on development for Ethereum Swarm, specifically authoring the implementations of PSS (messaging layer) and the first iteration of Mutable Resource Updates.

## Skills wanted

Since I'm most familiar with go-ethereum, I'd prefer to use that node. This project probably doesn't need a UX at this stage.

* Economist to model the cycling nature of such a token economy.
* Test network infrastructure (docker stuff etc)
* golang / go-ethereum

## Communication

Since I don't use a smart phone (it's the most evil device in history, didn't you know?) I can be contacted on https://gitter.im/nolash or grab hold of me at the event; I'm either in a digit covered red shirt with white collar or an orange swarm hoodie.

**Comment by bijanshahrokhi** [comment]
I have some experience around economics and token economy. My last hackathon project was tokenization of food co-ops which has some similarity to your idea. Let me know if you are interested in working. I'm a product manager with technical and business background

**Comment by nolash** [comment]
@bijanshahrokhi Let's have a chat! I'm in red shirt with white collar and swedish tie. I'll roam a bit, maybe you'll spot me?

**Comment by bijanshahrokhi** [comment]
Do you want to meet by the area that has coffee?

**Comment by nolash** [comment]
I will come over to the coffee area 22:30 ok?

**Comment by bijanshahrokhi** [comment]
Sure
I'm wearing white t shirt

**Comment by nolash** [comment]
I'm here now sitting down at table in front of monitor facing the bar.

**Comment by FollowJack** [comment]
Hi noLash. We are late. On our way. See ya soon

**Comment by kolinko** [comment]
If you're still looking for someone to talk about the token economics, chat me up.

Also, the project slightly reminds me of MetaliCoin ( https://www.metalicoin.com/ , with "i" in the middle, not to be confused with MetalCoin) - they are people from Australia who crowdfund metal mines and then distribute profits to the investors. Perhaps you can chat them up on Telegram, or I can get you a direct intro?

**Comment by nolash** [comment]
@kolinko Great! Will you be here after hackathon submission tomorrow 11:30 am? We could meet then. Otherwise, I'll wrestle away from the hacking (a different project) for awhile today.

**Comment by nolash** [comment]
@kolinko are you still around? I'm in an orange swarm hoodie. Feel free to grab hold of me if you spot me!
