### ISSUE TITLE
Looking for a cool team to learn from other hackers and contribute

### ISSUE THREAD

**Issue by v-almonacid** [ethberlin-hackathon/ETHBerlin-Teambuilding#53]
## Background
My background is in satellite communications engineering (got a PhD* in that field).
Last year I co-founded https://legacy.network/ (Ethereum-based project) and was the main author of the white paper. I also contributed with the architecture.
This year I've been working in chainimpact.io, a blockchain consulting company. So I threw away a career in the space field to concentrate myself in blockchain. I'm really passionate about the whole idea of decentralisation.  

## Skills
First, I don't consider myself a hacker _yet_. But I'm learning and that's one of the reasons I'm here. 
I have some general, non-professional, knowledge in:

_Some_ solidity and vyper (built some basic prototypes)
Software development, mainly Python
Web (Django and some html/css, javascript)

Of course, I've have a pretty good idea about how blockchains work ;)
My experience is more in engineering (signal processing and networking), prototyping and simulation. During my PhD thesis I built a Matlab simulator for a Cubesat IoT communication protocol.
Anyway, I'm sure I'll find a way to contribute while learning from others.

## Communication
I recently broke my phone screen and I can't use status. You can reach me by mail to ealmonacid at the big brother.

**Comment by ghost** [comment]
check out my idea: https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/58
Telegram:
@acrdlph

**Comment by bijanshahrokhi** [comment]
Hey 
Interested in talking. Are you here? 
I am happy to work on a new idea or the one I posted #31. Let me know. 
I have a very good knowledge of blockchain and ethereum as a product manager

**Comment by achillrudolph** [comment]
unfortunately, my team has already filled up

**Comment by v-almonacid** [comment]
Hey, thanks for reaching out, I finally found a team. Good luck ;)
