### ISSUE TITLE
Relayer for layer 2 execution markets

### ISSUE THREAD

**Issue by s1na** [ethberlin-hackathon/ETHBerlin-Teambuilding#54]
## Pitch

Various projects aim to improve user experience by enabling recurring fee subscriptions, delegated conditional execution or sponsored gas. These second layer execution markets all share the need for a mechanism that submit signed user transactions to the network. We hope to implement a modular relayer that fulfills these requirements. 

## Team

[Yotam](https://github.com/hemulin) and me are super excited to be attending ethberlin, and are looking forward to meeting you all, and learning from you.

To learn more about us, you can also read the [community introduction](https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/30) issue. 

## Skills wanted

We'll be happy to have passionate people join, regardless of background and skills. We can easily extend the idea based on your interests. For example, if you're a UI dev, we could additionally create a small cool dapp that uses the relayer. 

## Communication

If you're interested, don't hesitate to contact us on Riot, in our [gitter](https://gitter.im/planet-ethereum/Lobby), or by simply commenting here. Looking forward to hearing from you :)

**Comment by mikhaildobs** [comment]
Hi, I would love to join the team, as I work on a project (https://eth2.io) that could utilise the 2nd layer execution market. 
I'm also excited about what possibilities 2nd layer execution market could bring. (Universal Logins, subscriptions, etc) 
I'm a fullstack developer (React, NodeJs) with some experience of writing smart contracts.

Cheers!

**Comment by s1na** [comment]
Hey @dobrokhvalov, glad to hear you're interested, we'd be happy to have you on board :) I'm at Görlitzer Park factory, if you're also here we can have a talk.
