### ISSUE TITLE
GeoETH - Verifiable, On-Chain Geocaching

### ISSUE THREAD

**Issue by NoahZinsmeister** [ethberlin-hackathon/ETHBerlin-Teambuilding#56]
## Pitch

We're going to be designing a smart contract & frontend that lets users search for 'caches' in the real world, with a guaranteed prize if they are the first to find them all! This will involved smart contract coding, building a frontend in React, and some clever marketing/product work.

## Team

Team member 1: Blockchain dev at [Hydrogen](https://www.hydrogenplatform.com/), will work on React frontend.
Team member 2: Data analyst at [Coinbase](https://www.coinbase.com/), will work on smart contract code.
Team member 3: Blockchain dev at [Hydrogen](https://www.hydrogenplatform.com/), will work on smart contract.

We're looking for another team member who's interested in the product side of things - UI design, marketing, and general product design. While we will be able to handle most of the coding, we're open to suggestions and help on that side as well!

## Communication

Feel free to comment below with questions/comments!

**Comment by alexkroeger** [comment]
Team member 2 👋

**Comment by 8lcarte** [comment]
Hey guys I’m potentially interested in helping out. Have you seen the work the Pokt team did at ETHBuenosAires? Check it out here:
https://bananoquest.com/

**Comment by JosefJ** [comment]
I could help here as a solidity dev as well :) 

Btw, this thing is going on for Devcon4, so there is a potential extension into that project. 
https://docs.google.com/document/d/1ZAzJsbtCnCNdaL1DfAxmc7-4gfRvhwPQaBqiyHjpUqA/edit?usp=sharing
