### ISSUE TITLE
hacker would please like a team :]

### ISSUE THREAD

**Issue by katotopark** [ethberlin-hackathon/ETHBerlin-Teambuilding#6]
## Background

I'm Özgür, a 33 years old person from Bremen, Germany. I originally come from a traditional architectural design background but I've been writing code since the last 3 years having started with generative/creative coding for interactive applications. For the last year I've been working as a web developer for an academic research group.
At the moment I'm working on my master's thesis (already 2,5 months in) which is intended to be  manifested as a speculative/experimental Cryptocollectible world. I'm also deeply immersed in the theoretical side of things as in societal repercussions of decentralization.

## Skills

vuejs, nuxtjs, adonisjs, d3js, p5js 
ipfs
solidity, web3, truffle

2D/3D graphic/animation packages

## Communication

here's me on Riot: https://matrix.to/#/@ozko:matrix.org

happy to provide more info when needed.
HMU! ✌️

**Comment by yasinskyy** [comment]
Hi @katotopark ,

I am a member of team that consists from 3 enthusiastic developers that are going to visit ETHBerlin and take part in the hackathon. We are working on a project that will allow to combine the power of blockchain and smart contracts with ease of use and beautiful design for end users. If you are still interested in finding a team, please let me know. Would be great to work with somebody like you. Thanks!

All the best,
Yuriy

**Comment by ghost** [comment]
are you interested in the attention economy and blockchain-powered curation? if yes, consider joining me in building https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/58

**Comment by yasinskyy** [comment]
Thanks, the offer is interesting but I already have a team.

Good luck,
Yuriy Yasinskyy

пт, 7 вер. 2018 о 16:10 achillrudolph <notifications@github.com> пише:

**Comment by yasinskyy** [comment]
Hi! The offer is great, thanks, but I already have a team!

Good luck,
Yuriy Yasinskyy
