### ISSUE TITLE
Hacker searches Team

### ISSUE THREAD

**Issue by FollowJack** [ethberlin-hackathon/ETHBerlin-Teambuilding#60]
Hacker looks for motivated team.

I am here to learn and contribute.

My skills:

- Javascript: main language. Frontend Frameworks like Angular and React. Node 
- Solidity: Smaller contracts 
- Web3: build already smaller dapps. 

Looking forward to hear from you.

Best regards
Deni

**Comment by ghost** [comment]
Hi - I am building this: https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/58 but still on my own. if you are interested in curation markets, we should team up!

**Comment by FollowJack** [comment]
Hi achil. I remeber you from ethcamp here in berlin. Actually we are two devs. I will show it to my friend and respond to you

**Comment by vlad-kahoun** [comment]
HI Deni, I'm working on #52 Still looking for teammates. Please check it out.

**Comment by RachBLondon** [comment]
Hi Jack!

We are a team of two with front-end and some solidity experience -> but could probably do with another pair of hands. Building a cool habbit forming DAPP  ➡️https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/51

Let me know if you are interested!

Rach
