### ISSUE TITLE
SensorTRX - decentralised transaction relay managed by a smart contract

### ISSUE THREAD

**Issue by jakub-wojciechowski** [ethberlin-hackathon/ETHBerlin-Teambuilding#61]
## Pitch

Hi everyone psyched about this weekend! The Alice team will be working on a new kind of decentralised transaction relay with a bounty system that allows you to manage a network of sensor oracles. We want to build a system when sensors don't need a node access and the gas payments will be sponsored by a smart-contract. Data transactions should be available to be picked up by any actor who will be compensated not only for the gas costs but can also earn a little bonus for submitting a sign transaction to the network. We'd love to explore possibilities to further reduce gas costs but optimistically recording the data with a stake with a possibility to be challenged with a signed data. 

## Team

Alice Team: Kuba, Raph and Alex (alice.si, https://github.com/alice-si/)

## Skills wanted

UX, some solidity, crypto-protocols magicians 

## Communication

0x04f9d7e9ed4486b9ca6ced8f29910de84101a73d8840577e8ce3aed2b9954cdba6a26bb1fbca8af6f67205b49d1dfd4b823dbf1e6f8cae9822075c22b8513bef45

**Comment by s1na** [comment]
Hey @jakub-wojciechowski, I'd love to hear more about your idea, we had a related topic in mind. I'm at the Goerlitzer venue, if you're around maybe we can meet for a chat.

**Comment by jakub-wojciechowski** [comment]
Awesome, yes we are at the Goerlitzer. Let's chat and try to meet after the evening talks are over. You can use a telegram channel: https://t.me/joinchat/AAAAAEeU_twnBaTcp6rB2Q

**Comment by s1na** [comment]
I joined, but can't write as it's a one way channel. Maybe you can write there your whereabouts.

**Comment by jakub-wojciechowski** [comment]
Aghh, sorry, I've messed with the setting, please use this link: https://t.me/joinchat/BZ1DGBEhSfKOYKtn_ST5gg
