### ISSUE TITLE
Smart contract development lifecycle event tracker

### ISSUE THREAD

**Issue by rpavlovs** [ethberlin-hackathon/ETHBerlin-Teambuilding#62]
## Pitch

The idea is to communicate smart contract security to the general public by creating a browsable history of the steps of the development of a smart contract.

We will make a token that will allow recording of each step of the development of a smart contract. Steps can include:
- deployment to mainnet
- audit for mainnet deployment
- deployment to testnet
- audit for testnet deployment
- started a bounty program
- paid out a bounty on the program
- initial software assessment
- code review complete
- incident occurred
- incident response took place
- upgrade occurred

This information has many potential benefits:
- supplies data to determine a level of trust for a contract
- allows investigation of the quality process used in the contract development
- supplies data to determine the reputation of auditors and developers

The token will include the sender address (perhaps the auditor), the developer address, the link to previous tokens (think of a chain of events) and an IPFS link that stores event details.

## Team

I (Roman) am a full stack JS developer (Node.js + ReactNative). I have experience making small projects with Truffle, web3, Solidity, 0x, Toshi.

@RexShinka (Rex) is a system engineer and involved with #EthSecurity building the quality/security guidelines and infrastructure (of which this token will be a part).

This is my 3rd and Rex's 2rd ETH* hackathon.

## Skills wanted

We are looking need an experienced solidity developer.

## Communication

Status/Riot/Telegram: **rpavlovs**
Status/Telegram: **ShinkaRex**

**Comment by ligi** [comment]
You might be interested in these worshop notes from securETH: https://ethereum-magicians.org/t/secureth-workshop-notes-open-source-code-assessment-721-assessment-stamp

**Comment by rpavlovs** [comment]
Thank you for the amazing notes!
