### ISSUE TITLE
Reopening liberate your books proposal

### ISSUE THREAD

**Issue by tkalfigo** [ethberlin-hackathon/ETHBerlin-Teambuilding#63]
This is about reopening issue https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/23 which the initial proposer abandoned and agreed for me to take it over.

The linked description is an initial start point. There are several ways this can play out and things are open to discussion.

We are 2 devs so far and looking for at least 1-2 more devs, preferably someone with solid solidity skills. Optional: experience with erc721 non-fungible tokens for physical objects. 

The idea is a good match for a blockchain as:
    * it facilitates the direct and unhindered payment of a deposit for the book i.e. no central payment authority to lock/block deposit payments
    * the history of payments, change of ownership and lending requests can be transparently recorded in the contract

**Comment by gautamdhameja** [comment]
Hi @tkalfigo, I'm interested in building this and also looking for a team.  How can I contact you?

**Comment by palevoo** [comment]
+

**Comment by palevoo** [comment]
hey, im a fullstack js dev with some solidity experience, would love to join :)

**Comment by tkalfigo** [comment]
@palevoo Cool! Let's meet at 22:30 at the registration at the entrance.
