### ISSUE TITLE
Open database of blockchain metadata

### ISSUE THREAD

**Issue by kolinko** [ethberlin-hackathon/ETHBerlin-Teambuilding#64]
## Pitch

There is a lot of metadata surrounding Ethereum contracts - information about the creators (who, what site, etc), contract source code, and so on. While the access to blockchain data is free and open to everyone, the metadata is often hosted by commercial entities (e.g. etherscan) which may not necessarily welcome grabbing it in bulk.

During the hackathon we will research all the databases and catalogues of metadata. If there is nothing good enough, we will build our own, and if there are some good options out there - at least we'll build a catalogue of all the metadata sources :)

*Tell us what your idea is and why it's great*

Working on our projects (Trivial.co and Solidstamp) we discovered how irritating it is that there are very few sources of meta information that you can just grab and use in your project at will. We hope that if a good database exists, it will help many projects - new blockchain explorers that pop up, researchers who would like to grab contract source codes in bulk etc.

## Team

Kuba Lipiński - founder of SolidStamp (a service publishing smart contract verification info), co-founder of Polidea

Tomasz Kolinko - co-founder of Trivial.co (a token explorer), and Orisi (first ever decentralised oracles system)

We plan to play with the idea for the weekend, and see whether there is something to it :)

## Skills wanted

Not much programming needed, but a willingness to research and integrate databases very much so :)

**Comment by pascalvanhecke** [comment]
Where are you guys located in the building?

(Now that the hackathon has started, this is useful info to add :-) )

**Comment by kolinko** [comment]
Ah, @pascalvanhecke beanbags on the ground floor - in the last room on the left from the entrance. Come over if you're still around!
