### ISSUE TITLE
Mobile Dev looking to get decentralised 

### ISSUE THREAD

**Issue by mel3239113** [ethberlin-hackathon/ETHBerlin-Teambuilding#68]
Keep in short and sweet.

Working as an iOS dev in Berlin for the past two years.
Skills
iOS development and playing around with smart contracts in my spare time.

pretty new to the eth space but keen to jump on in and learn as i go.

Cheers.

**Comment by manhlx3006** [comment]
Hi, how could I talk to you face-to-face?

**Comment by ligi** [comment]
Dam iOS ;-) - If you want to dig into android #32 might be an option

**Comment by skywinder** [comment]
Let's get rock ETH + mobile world altogether! 
@mel3239113 welcome to discuss iOS things with our team! fire me a message :)
We are in Full Node on the 1st floor

+
https://github.com/matterinc/DiveLane

**Comment by manhlx3006** [comment]
Hi @skywinder 
I'm Mike from Kyber Network.
I'm working on a Ethereum wallet and a library for buying goods/services or even tokens from any ERC20 tokens (check out my repo here https://github.com/KyberNetwork/widget-swift).
If you're still around ETH Berlin may be we could meet and talk more.

**Comment by NoahMarconi** [comment]
@manhlx3006 are you around after the winner announcement? I'd love to chat about your wallet as well

**Comment by manhlx3006** [comment]
@NoahMarconi Sure. I'm near Status booth in backyard (where we got food for dinner).

**Comment by NoahMarconi** [comment]
Cool I'll come find you after the winner announcements.

Msg if you head elsewhere afterwards :)

**Comment by manhlx3006** [comment]
Hi are you still around? I’m near the door in backyard (near Status & Skale booth)
