### ISSUE TITLE
Refined Etherscan 

### ISSUE THREAD

**Issue by krzkaczor** [ethberlin-hackathon/ETHBerlin-Teambuilding#69]
## Pitch

Add additional features, aiding debugging to etherscan.com as a browser plugin. Think of [refined-github](https://github.com/sindresorhus/refined-github) for etherscan.

Repo: https://github.com/krzkaczor/refined-etherscan

Ideas for features:
- automatically decode tx data to abi calls (ex: `function_call(arg1, arg2)` instead of `0x12412412137`)
- prettify print transaction (`Trade: 1.00 TCT for 0.00366 ETH total`)
- name contracts/addresses and expose it in UI
- `Contract Source Code` explorer overhaul (code formatting, hover to read storage variable etc)
- more? please post ideas as comments here.

Team:
- me 
- @kolinko (maybe)

**Comment by kolinko** [comment]
+ pretty print transaction details
+ warnings about scammy tokens?

**Comment by krzkaczor** [comment]
@kolinko 
> - pretty print transaction details 

does `automatically decode tx data to abi calls` cover it? could you leave some examples?

> - warnings about scammy tokens?

any nice database/api that we could use for that? Honestly I thought to focus on debugging related features for now.

**Comment by krzkaczor** [comment]
New idea:
- add ability to define names for contracts, make it visible and overwrite title tag

**Comment by kolinko** [comment]
> > pretty print transaction details
> does automatically decode tx data to abi calls cover it? could you leave some examples?

Nope. If you look at this EtherDelta tx on Trivial:

https://trivial.co/transaction/0x17ae0409900235e2d349ff1865eb9371e6154e1bf7da7c88604e664a2acd789e

It has parameters decoded into json ABI (although formatted poorly), and a pretty-print version on top.

The pretty-print is this:
`Trade: 1.00 TCT for 0.00366 ETH total`

Parameters are these:
```
u 'parameters': {
	u 'nonce': 54010927106,
	u 'amountGet': 3663003663003663,
	u 'expires': 90000000,
	u 's': 0,
	u 'amount': 3663003663003663,
	u 'r': 0,
	u 'user': u '0xcd4d244e415f3704213b534509aa7eb51d92ee65',
	u 'amountGive': 1,
	u 'v': 0,
	u 'tokenGive': u '0x55fc04a73f058832b4f3498dc83ceb6e53a9e314',
	u 'tokenGet': u '0x0000000000000000000000000000000000000000'
}
```

For pretty-print you need to understand what the tx really represents, sometimes fetch some extra data (that '0x55fc04a73f058832b4f3498dc83ceb6e53a9e314' tokenGive is actually TCT tokens), and parse some other (that "for XX total" = amount / amountGet, and nicely converted into ETH).

Parameters are good for some debugging purposes, pretty printing is good for some others (when we were debugging our interface into EtherDelta, before the pretty print, I had to constantly do a lot of divisions and converting from hex/decimal into proper amounts)

**Comment by krzkaczor** [comment]
@kolinko okay, makes sense but i think that decoding ABI is a first step, enabling this. I am gonna maintain list of features in first post here.
