### ISSUE TITLE
Selling tickets for events like DEVCON, Boom or Burning Man sucks - we can do better, can't we?

### ISSUE THREAD

**Issue by stefek99** [ethberlin-hackathon/ETHBerlin-Teambuilding#7]
## Pitch

Some events are massively oversubscribed.

Increasing ticket price is not really an option - they are already expensive - and we want to be inclusive.

What would be a fair ticketing system?

Check **Chaos Communication Congress**: https://tickets.events.ccc.de/34c3/docs/

> Phase 1, only people with a voucher can buy a ticket. 

> During this phase, some vouchers will create new vouchers after they have been redeemed and the order has been paid for. If your voucher replicates, we will ask you for an email address to which we should send the new voucher.

Initial group of 256 ambassadors, core team members who receives initial vouchers and as they buy the tickets, they pass on voucher information...

## Team

`TBD`

## Skills wanted

`TBD`

## Communication

`+44 758 629 4279`

I have so many notifications everywhere I've declared bankruptcy.

Mobile phone works well, FaceTime, iMessage, WhatsApp will work.

**Comment by ligi** [comment]
The system that the CCC uses is FOSS: https://pretix.eu/about/en

Would be interested to do something in this area at ethberlin - already laid down a cornerstone a while ago:  https://espass.it

**Comment by stefek99** [comment]
WOW.

It seems like the problem is being solved.

I was thinking about some general principles:
* transferring tickets
* avoiding touting _(hoarding tickets for profit)_
* tracking affiliates / promoters
* allowing less-financially able people to have a chance
* allowing very-financially able to just buy the f•••ing ticket because the price doesn't matter _(think $1200 tier for Burning Man)_

If this is a blockchain system, thinking how to store data in a trustless manner on-chain / off-chain without exposing data (promo codes) to everyone...

---

I'm not saying I know the answers, I'm saying it's an interesting problem with some existing work already happening in the space.

**Comment by stefek99** [comment]
Update: https://twitter.com/MichalStefanow/status/1035843631448502272

_(cannot make it)_
