### ISSUE TITLE
Hopeful Hacker looking for a terrific team!

### ISSUE THREAD

**Issue by SamTS** [ethberlin-hackathon/ETHBerlin-Teambuilding#9]
## Background
Hi! 
My name's Sam, I'm a 28 year old programmer from NYC, pretty new to the blockchain scene and am super excited to participate in my first Ethereum hackathon. 

## Skills
True fullstack, but more specifically for this hackathon:

- Anything JS (React, Redux, Angular, Hand rolled, Node, web3.js)
- LIbp2p 
- Solidity (although not my strongest suit, yet!)

## Communication
Email : sstrauch25@gmail.com

**Comment by sebastiandigi** [comment]
hey mate,
would be awesome to have you aboard of my journalism project - check that out: https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/21
